#ifndef PROTOCOL_H
#define PROTOCOL_H
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#define  PARTIAL_FILE_SIZE 4096
typedef unsigned int uint;
enum ENUM_MSG_TYPE
{
    ENUM_MSG_TYPE_MIN = 0,
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_SEARCH_USER_REQUEST,
    ENUM_MSG_TYPE_SEARCH_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_RESPOND,
    ENUM_MSG_TYPE_REFRESH_REQUEST,
    ENUM_MSG_TYPE_REFRESH_RESPOND,
    ENUM_MSG_TYPE_REFRESH_SIGNATURE_REQUEST,
    ENUM_MSG_TYPE_REFRESH_SIGNATURE_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_CREATE_DIR_REQUEST,
    ENUM_MSG_CREATE_DIR_RESPOND,
    ENUM_MSG_FLUSH_FILE_REQUEST,
    ENUM_MSG_FLUSH_FILE_RESPOND,
    ENUM_MSG_DELETE_DIR_REQUEST,
    ENUM_MSG_DELETE_DIR_RESPOND,
    ENUM_MSG_RENAME_FILE_REQUEST,
    ENUM_MSG_RENAME_FILE_RESPOND,
    ENUM_MSG_TYPE_MOVE_FILE_REQUEST,
    ENUM_MSG_TYPE_MOVE_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,
    ENUM_MSG_TYPE_DELETE_FILE_REQUEST,
    ENUM_MSG_TYPE_DELETE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_AGREE_REQUEST,
    ENUM_MSG_TYPE_SHARE_AGREE_RESPOND,
    ENUM_MSG_TYPE_CHAT_IMG_REQUEST,
    ENUM_MSG_TYPE_CHAT_IMG_RESPOND,
    ENUM_MSG_TYPE_CHAT_IMG_AGREE_REQUEST,
    ENUM_MSG_TYPE_CHAT_IMG_AGREE_RESPOND,
    ENUM_MSG_TYPE_CHAT_IMG_DATA_REQUEST,
    ENUM_MSG_TYPE_CHAT_IMG_DATA_RESPOND,
    ENUM_MSG_TYPE_CHAT_IMG_DATA_RES_REQUEST,
    ENUM_MSG_TYPE_CHAT_IMG_DATA_RES_RESPOND,
    ENUM_MSG_TYPE_FRIEND_MANAGE_REFRESH_REQUEST,
    ENUM_MSG_TYPE_FRIEND_MANAGE_REFRESH_RESPOND,
    ENUM_MSG_TYPE_MAX = 0x00fffffffff,
};

//协议数据单元 Protocol Data Unit
struct PDU
{
    uint uiPDUlen;
    uint uiMsgType;
    uint uiMsgLen;
    char caData[64];
    char caMsg[];
};

struct FileInfo
{
    char caName[32];
    int iFileType;
};

PDU* mkpdu(uint uimsglen);
#endif
